* NumberTheory

* Division
  1. a|0, 1|a, a|a
  2. a|1 if and only if a = 1.
  3. if a|b and c|d then ac|bd
  4. if a|b and b|c then a|c
  5. if a|b and b|a if and only if a = [+|-]b
  6. if a|b and b!=0 then |a| <= |b|
  7. if a|b and a|c then a|(bx+cy) for arbitary integers x and y.

* Theorems
  1. given integers a and b, not both of which are zero, threre exist
     interers x and y such that gcd(a,b) = ax+by.
  2. If a and b are given intergers, not both of which are zero, then the set
     T = { ax+by | x,y are integers } is precisely the set of all multiples of
     d = gcd(a,b). Corollary of 1.
  3. if a and b be integers not both of them zero, then a and b are relatively
     prime if and only if three exist integers x and y such that ax by = 1
  4. If a|c and b|c, with gcd(a,b) = 1, then ab|c.
  5. if a|bc with gcd(a,b) =1 then a|c.

* prime numbers
  An integer p > 1 is called prime number, or simpley a prime, if its
only positive divisors are 1 and p. And integer greater than 1 that is
not a prime is termed composite.

  1. If p is a prime and p|ab, then  p|a or p|b.
  2. If p is a prime and p|a_1,a_2,a_3...a_n then p|a_k for some k, where 1<=k<=n.
  3. If p is a prime and p|q_1,q_1,q_3..q_n then p=q_k for some k, whre 1<=k<=n.
  4. Every positve integer n>1 can be expressed as a product of
     primes; this representation is uniqueu, apart from the order in
     which the factors occur.
  5. There are infinite number of primes.
  6. p_n <= p_1.p_2.p_3...p_(n_1) + 1  n >= 2
  7. (p_n)^2 < p_1.p_2.p_3..p_(n-1)    n >= 5
  8. if p_n is nth prime number then p_n <= 2^(2^(n-1))
  9. there are at least n+1 primes less than 2^(2^n)
  10. There are infinite prime numbers of form 4n+3. 
  11. If a and b are relatively prime numbers then the arithmetic progression a,a+b,a+2b ... contains infinitely many primes.
  
Conjectures.
  1. There are infinite twin prime paire (twin prime: if a is prime the a+2 is also
     a prime).
  2. Every even integer > 4 can be represented at sum of two prime numbers. (Godbatch)
  3. Any even integer (>=6) of form 4n+2 is a sum of two numbers each
     being either a prime of the 4n+1 or 1.
  4. Every odd interger can be represented as sum of three primes (this is proved
     for sufficienlty large n, n> 10^1346, in 2002)


